### ISSUE TITLE
Can't compile!

### ISSUE THREAD

**Issue by TheMegafuji** [ayildirim/OpenVR#1]
I am running the same code as the example from the folder and this happens:

```
Final_arduino_code.ino: In function 'void read_sensors()':
Final_arduino_code:427: error: 'Read_Gyro' was not declared in this scope
Final_arduino_code:428: error: 'Read_Accel' was not declared in this scope
Final_arduino_code:429: error: 'Read_Magn' was not declared in this scope
Final_arduino_code.ino: In function 'void reset_sensor_fusion()':
Final_arduino_code:450: error: 'Vector_Cross_Product' was not declared in this scope
Final_arduino_code:458: error: 'Compass_Heading' was not declared in this scope
Final_arduino_code:462: error: 'init_rotation_matrix' was not declared in this scope
Final_arduino_code.ino: In function 'void compensate_sensor_errors()':
Final_arduino_code:476: error: 'Matrix_Vector_Multiply' was not declared in this scope
Final_arduino_code.ino: In function 'void setup()':
Final_arduino_code:541: error: 'I2C_Init' was not declared in this scope
Final_arduino_code:542: error: 'Accel_Init' was not declared in this scope
Final_arduino_code:543: error: 'Magn_Init' was not declared in this scope
Final_arduino_code:544: error: 'Gyro_Init' was not declared in this scope
Final_arduino_code.ino: In function 'void loop()':
Final_arduino_code:675: error: 'output_calibration' was not declared in this scope
Final_arduino_code:683: error: 'Compass_Heading' was not declared in this scope
Final_arduino_code:684: error: 'Matrix_update' was not declared in this scope
Final_arduino_code:685: error: 'Normalize' was not declared in this scope
Final_arduino_code:686: error: 'Drift_correction' was not declared in this scope
Final_arduino_code:687: error: 'Euler_angles' was not declared in this scope
Final_arduino_code:689: error: 'output_angles' was not declared in this scope
Final_arduino_code:693: error: 'output_sensors' was not declared in this scope
```

I can't get it to work, these errors normally appear because of a missing library, I already tried to include the .ino in the rest of the folders, didn't worked, created a .h to each of the .ino files and renamed the ino to cpp and didn't work, I don't know how to get rid of this problem, please help me.

**Comment by simonamdev** [comment]
Hi, I have the same problem and I have not managed to get it working yet either. @ayildirim can you help?

**Comment by maxabrahamsson** [comment]
You know when you try opening an INO file, Arduino IDE asks you if you would like to create a new folder for that specific file.

If you click yes, it seperates that file into a new folder.

If I remember correctly you should either press “No” then add other files as new tabs.
If you click “Yes”, then add other files into new created folder and then open them all in new tabs.

I hope it helps

**Comment by simonamdev** [comment]
Hi,

Probably from an update to the IDE but there isn't a no option, only cancel. I got around this by opening arduino_final, clicking yes, then moving all of the files to that new folder and opening it again. Thanks for your help!
