### ISSUE TITLE
programmer is not responding

### ISSUE THREAD

**Issue by qiaolan98** [ayildirim/OpenVR#2]
I have uploaded the code many times and Arduino says me that the programmer is not responding.

avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
Problema subiendo a la placa. Visita http://www.arduino.cc/en/Guide/Troubleshooting#upload para sugerencias.
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0x4f
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0x4f

**Comment by qiaolan98** [comment]
@ayildirim Can you help me, please?

**Comment by qiaolan98** [comment]
Arduino:1.6.11 (Windows 10), Tarjeta:"Arduino Pro or Pro Mini, ATmega328 (5V, 16 MHz)"

El Sketch usa 14.920 bytes (48%) del espacio de almacenamiento de programa. El máximo es 30.720 bytes.
Las variables Globales usan 1.027 bytes (50%) de la memoria dinámica, dejando 1.021 bytes para las variables locales. El máximo es 2.048 bytes.
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 3 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 4 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 5 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 6 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 7 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 8 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 9 of 10: not in sync: resp=0xa1
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 10 of 10: not in sync: resp=0xa1
Problema subiendo a la placa. Visita http://www.arduino.cc/en/Guide/Troubleshooting#upload para sugerencias.

Este reporte podría tener más información con
"Mostrar salida detallada durante la compilación"
opción habilitada en Archivo -> Preferencias.

**Comment by maxabrahamsson** [comment]
You have to press reset button Arduino Mini Pro in same time you press Upload on Arduino IDE. Because Arduino Mini Pro does not have auto-reset functionality. It is tricky to catch right timing for this. Please try again and again until you get it right.

**Comment by qiaolan98** [comment]
Ok. I'll try it. Thank you so much.

**Comment by qiaolan98** [comment]
But now I have another problem, in processing software says me that I haven't set the right serial port and I don't know what does it mean

**Comment by qiaolan98** [comment]
HAVE A LOOK AT THE LIST ABOVE AND SET THE RIGHT SERIAL PORT NUMBER IN THE CODE!
  -> Using port 0: COM7
Trying to setup and synch Razor...

**Comment by qiaolan98** [comment]
// Setup graphics
  size(640, 480, OPENGL);
(in pocessing software says OPENGL is deprecated)

**Comment by qiaolan98** [comment]
@ayildirim What should I do?

**Comment by maxabrahamsson** [comment]
@qiaolan98 
Processing and calibration is from this source. Please check tutorial and updated script on this repository.
https://github.com/ptrbrtz/razor-9dof-ahrs/wiki/Tutorial#sensor-calibration

**Comment by qiaolan98** [comment]
I have tried, but it doesn't work

El 21 nov. 2016 12:33, "Ahmet YILDIRIM" notifications@github.com escribió:

@qiaolan98 https://github.com/qiaolan98
Processing and calibration is from this source. Please check tutorial and
updated script on this repository.
https://github.com/ptrbrtz/razor-9dof-ahrs/wiki/Tutorial#sensor-calibration

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/ayildirim/OpenVR/issues/2#issuecomment-261913556, or mute
the thread

**Comment by qiaolan98** [comment]
Could I do it with an Arduino UNO + MPU-6050?

**Comment by maxabrahamsson** [comment]
@qiaolan98 : If razor-9dof-ahrs calibration tutorial did not work, please ask to developer of that repository. I do not know what may the cause of problem.

Yes, You can use MPU-6050. If you can set it up as AHRS IMU and export same values like this. Then it will work with same FreePie script. Because FreePie script that I shared expect values like "ahrsImu.yaw", "ahrsImu.pitch". If it is not in this format, then you have to fix and make it in same format.

Good luck.
